name: circlify
description: "Circlify is a library for creating interactive pie charts and animated graphs with flexible customization and smooth animations."
version: 2.0.0

repository: https://github.com/zeffbtw/Circlify
homepage: https://github.com/zeffbtw/Circlify
issue_tracker: https://github.com/zeffbtw/Circlify/issues
topics:
  - chart
  - animation
  - ui
  - effects
  - widget

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
